user: user1
password: supersecret
password_bcrypt: ""
cluster_admin: false

credentials:
  usePasswordGenerator: false # use mittwalds password generator

cluster_name: training
cluster_domain: cluster.acend.ch

createNamespaces:
  default: true
  vmimages: false
  quota: true
  monitoring: false
  argoCD: true

createSecrets:
  userConfig: true
  basicAuth: true
